version: "3"

services: 
  jupyter_lab:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    ports: 
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: apple
            count: 1
            capabilities: [gpu]
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - ./notebooks:/tf/notebooks
